framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.cache_dir%/sessions'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
