<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250907233955 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Corrige as entidades para alinhar com o banco de dados, remove tabelas e colunas duplicadas/inconsistentes.';
    }

    public function up(Schema $schema): void
    {
        // ETAPA 1: Remover todas as CONSTRAINTS que causam conflito ANTES de qualquer outra operação.
        $this->addSql('ALTER TABLE IF EXISTS agencias DROP CONSTRAINT IF EXISTS agencias_codigo_id_banco_key');
        $this->addSql('ALTER TABLE IF EXISTS bancos DROP CONSTRAINT IF EXISTS bancos_numero_key');
        $this->addSql('ALTER TABLE IF EXISTS chaves_pix DROP CONSTRAINT IF EXISTS chaves_pix_chave_pix_id_tipo_chave_key');
        $this->addSql('ALTER TABLE IF EXISTS contas_vinculadas DROP CONSTRAINT IF EXISTS contas_vinculadas_id_conta_principal_id_conta_vinculada_tip_key');
        $this->addSql('ALTER TABLE IF EXISTS estados DROP CONSTRAINT IF EXISTS estados_uf_key');
        $this->addSql('ALTER TABLE IF EXISTS failed_jobs DROP CONSTRAINT IF EXISTS failed_jobs_uuid_key');
        $this->addSql('ALTER TABLE IF EXISTS fiadores_inquilinos DROP CONSTRAINT IF EXISTS fiadores_inquilinos_id_fiador_id_inquilino_data_inicio_key');
        $this->addSql('ALTER TABLE IF EXISTS permissions DROP CONSTRAINT IF EXISTS permissions_name_guard_name_key');
        $this->addSql('ALTER TABLE IF EXISTS personal_access_tokens DROP CONSTRAINT IF EXISTS personal_access_tokens_token_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_contratantes DROP CONSTRAINT IF EXISTS pessoas_contratantes_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_corretoras DROP CONSTRAINT IF EXISTS pessoas_corretoras_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_corretores DROP CONSTRAINT IF EXISTS pessoas_corretores_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_corretores DROP CONSTRAINT IF EXISTS pessoas_corretores_creci_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_documentos DROP CONSTRAINT IF EXISTS pessoas_documentos_id_pessoa_id_tipo_documento_numero_docum_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_emails DROP CONSTRAINT IF EXISTS pessoas_emails_id_pessoa_id_email_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_fiadores DROP CONSTRAINT IF EXISTS pessoas_fiadores_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_locadores DROP CONSTRAINT IF EXISTS pessoas_locadores_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_pessoa_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_telefones DROP CONSTRAINT IF EXISTS pessoas_telefones_id_pessoa_id_telefone_key');
        $this->addSql('ALTER TABLE IF EXISTS pessoas_tipos DROP CONSTRAINT IF EXISTS pessoas_tipos_id_pessoa_id_tipo_pessoa_data_inicio_key');
        $this->addSql('ALTER TABLE IF EXISTS roles DROP CONSTRAINT IF EXISTS roles_name_guard_name_key');
        $this->addSql('ALTER TABLE IF EXISTS configuracoes_cobranca DROP CONSTRAINT IF EXISTS configuracoes_cobranca_id_conta_bancaria_key');


        // ETAPA 2: Executar o resto das operações
        $this->addSql('DROP TABLE IF EXISTS logradouro');
        $this->addSql('DROP INDEX IF EXISTS idx_agencias_codigo');
        $this->addSql('ALTER TABLE agencias DROP created_at');
        $this->addSql('ALTER TABLE agencias DROP updated_at');
        $this->addSql('ALTER TABLE agencias ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE agencias ALTER codigo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE agencias ALTER id_banco TYPE INT USING id_banco::integer');
        $this->addSql('ALTER TABLE agencias ALTER nome TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE agencias ALTER id_endereco TYPE INT USING id_endereco::integer');
        $this->addSql('ALTER TABLE agencias ADD CONSTRAINT FK_923688C0995BA0E1 FOREIGN KEY (id_banco) REFERENCES bancos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agencias ADD CONSTRAINT FK_923688C0A83B3A9B FOREIGN KEY (id_endereco) REFERENCES enderecos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_agencias_banco RENAME TO IDX_923688C0995BA0E1');
        $this->addSql('ALTER INDEX IF EXISTS idx_agencias_endereco RENAME TO IDX_923688C0A83B3A9B');
        $this->addSql('ALTER TABLE bairros DROP CONSTRAINT IF EXISTS bairros_id_cidade_fkey');
        $this->addSql('ALTER TABLE bairros DROP created_at');
        $this->addSql('ALTER TABLE bairros DROP updated_at');
        $this->addSql('ALTER TABLE bairros ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE bairros ALTER id_cidade TYPE INT USING id_cidade::integer');
        $this->addSql('ALTER TABLE bairros ALTER id_cidade DROP NOT NULL');
        $this->addSql('ALTER TABLE bairros ALTER codigo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE bairros ADD CONSTRAINT FK_6BE5C8B64CAF86B1 FOREIGN KEY (id_cidade) REFERENCES cidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_bairros_cidade RENAME TO IDX_6BE5C8B64CAF86B1');
        $this->addSql('ALTER TABLE bancos DROP created_at');
        $this->addSql('ALTER TABLE bancos DROP updated_at');
        $this->addSql('ALTER TABLE bancos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE bancos ALTER nome TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE chaves_pix DROP CONSTRAINT IF EXISTS chaves_pix_id_conta_bancaria_fkey');
        $this->addSql('ALTER TABLE chaves_pix DROP CONSTRAINT IF EXISTS chaves_pix_id_pessoa_fkey');
        $this->addSql('ALTER TABLE chaves_pix DROP CONSTRAINT IF EXISTS chaves_pix_id_tipo_chave_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_chaves_pix_chave');
        $this->addSql('DROP INDEX IF EXISTS idx_chaves_pix_conta');
        $this->addSql('DROP INDEX IF EXISTS idx_chaves_pix_pessoa');
        $this->addSql('DROP INDEX IF EXISTS idx_chaves_pix_tipo');
        $this->addSql('ALTER TABLE chaves_pix DROP created_at');
        $this->addSql('ALTER TABLE chaves_pix DROP updated_at');
        $this->addSql('ALTER TABLE chaves_pix ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE chaves_pix ALTER chave_pix TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE chaves_pix ALTER principal DROP DEFAULT');
        $this->addSql('ALTER TABLE chaves_pix ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE cidades DROP CONSTRAINT IF EXISTS cidades_id_estado_fkey');
        $this->addSql('ALTER TABLE cidades DROP created_at');
        $this->addSql('ALTER TABLE cidades DROP updated_at');
        $this->addSql('ALTER TABLE cidades ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE cidades ALTER id_estado TYPE INT USING id_estado::integer');
        $this->addSql('ALTER TABLE cidades ALTER id_estado DROP NOT NULL');
        $this->addSql('ALTER TABLE cidades ALTER codigo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE cidades ADD CONSTRAINT FK_79B94AE76A540E FOREIGN KEY (id_estado) REFERENCES estados (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_cidades_estado RENAME TO IDX_79B94AE76A540E');
        $this->addSql('ALTER TABLE configuracoes_cobranca DROP CONSTRAINT IF EXISTS configuracoes_cobranca_id_conta_bancaria_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_configuracoes_cobranca_conta');
        $this->addSql('ALTER TABLE configuracoes_cobranca DROP created_at');
        $this->addSql('ALTER TABLE configuracoes_cobranca DROP updated_at');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER carencia DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER carencia_cartorio DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER carencia_advocacia DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER multa_itau DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER mora_diaria DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER protesto DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER tipo_dias_protesto DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER dias_protesto DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER nao_gerar_judicial DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER tipo_arquivo DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER variacao_bb DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER mudar_especie DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_agencia_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_documento_titular_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_layout_remessa_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_pessoa_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_razao_conta_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_tipo_carteira_fkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT IF EXISTS contas_bancarias_id_tipo_remessa_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_contas_bancarias_ativo');
        $this->addSql('DROP INDEX IF EXISTS idx_contas_bancarias_principal');
        $this->addSql('DROP INDEX IF EXISTS IDX_E7120EDB5DACA326');
        $this->addSql('DROP INDEX IF EXISTS IDX_E7120EDBF4F27B3E');
        $this->addSql('DROP INDEX IF EXISTS IDX_E7120EDB9C6C76F9');
        $this->addSql('DROP INDEX IF EXISTS IDX_E7120EDB5890E32D');
        $this->addSql('DROP INDEX IF EXISTS IDX_E7120EDB8BD0CD78');
        $this->addSql('ALTER TABLE contas_bancarias DROP created_at');
        $this->addSql('ALTER TABLE contas_bancarias DROP updated_at');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_pessoa DROP NOT NULL');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_banco TYPE INT USING id_banco::integer');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_banco DROP NOT NULL');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_agencia TYPE INT USING id_agencia::integer');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_tipo_conta TYPE INT USING id_tipo_conta::integer');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id_tipo_conta DROP NOT NULL');
        $this->addSql('ALTER TABLE contas_bancarias ALTER codigo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_bancarias ALTER digito_conta TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_bancarias ALTER titular TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_bancarias ALTER principal DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER codigo_cedente TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE contas_bancarias ALTER registrada DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER aceita_multipag DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER convenio_sicredi TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_bancarias ALTER usa_endereco_cobranca DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER cobranca_compartilhada DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_bancarias ALTER descricao TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDB3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDB35F182E9 FOREIGN KEY (id_agencia) REFERENCES agencias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_contas_bancarias_pessoa RENAME TO IDX_E7120EDB3AE81E6F');
        $this->addSql('ALTER INDEX IF EXISTS idx_contas_bancarias_banco RENAME TO IDX_E7120EDB995BA0E1');
        $this->addSql('ALTER INDEX IF EXISTS idx_contas_bancarias_agencia RENAME TO IDX_E7120EDB35F182E9');
        $this->addSql('DROP INDEX IF EXISTS idx_contas_vinculadas_principal');
        $this->addSql('DROP INDEX IF EXISTS idx_contas_vinculadas_vinculada');
        $this->addSql('ALTER TABLE contas_vinculadas DROP created_at');
        $this->addSql('ALTER TABLE contas_vinculadas DROP updated_at');
        $this->addSql('ALTER TABLE contas_vinculadas ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE contas_vinculadas ALTER tipo_vinculo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE contas_vinculadas ALTER ativo DROP DEFAULT');
        $this->addSql('DROP INDEX IF EXISTS idx_emails_email');
        $this->addSql('ALTER TABLE emails DROP created_at');
        $this->addSql('ALTER TABLE emails DROP updated_at');
        $this->addSql('ALTER TABLE emails ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE emails ALTER id_tipo TYPE INT USING id_tipo::integer');
        $this->addSql('ALTER TABLE emails ALTER id_tipo DROP NOT NULL');
        $this->addSql('ALTER INDEX IF EXISTS idx_emails_tipo RENAME TO IDX_4C81E852FB0D0145');
        $this->addSql('ALTER TABLE enderecos DROP CONSTRAINT IF EXISTS enderecos_id_pessoa_fkey');
        $this->addSql('ALTER TABLE enderecos DROP created_at');
        $this->addSql('ALTER TABLE enderecos DROP updated_at');
        $this->addSql('ALTER TABLE enderecos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE enderecos ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE enderecos ALTER id_logradouro TYPE INT USING id_logradouro::integer');
        $this->addSql('ALTER TABLE enderecos ALTER id_tipo TYPE INT USING id_tipo::integer');
        $this->addSql('ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_enderecos_pessoa RENAME TO IDX_FC4E02DA3AE81E6F');
        $this->addSql('ALTER INDEX IF EXISTS idx_enderecos_logradouro RENAME TO IDX_FC4E02DAF1B90DAB');
        $this->addSql('ALTER INDEX IF EXISTS idx_enderecos_tipo RENAME TO IDX_FC4E02DAFB0D0145');
        $this->addSql('ALTER TABLE estados DROP created_at');
        $this->addSql('ALTER TABLE estados ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE estados ALTER uf TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE failed_jobs ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE failed_jobs ALTER failed_at DROP DEFAULT');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP CONSTRAINT IF EXISTS fiadores_inquilinos_id_fiador_fkey');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP CONSTRAINT IF EXISTS fiadores_inquilinos_id_inquilino_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_fiadores_inquilinos_fiador');
        $this->addSql('DROP INDEX IF EXISTS idx_fiadores_inquilinos_inquilino');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP created_at');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP updated_at');
        $this->addSql('ALTER TABLE fiadores_inquilinos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE fiadores_inquilinos ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE formas_retirada DROP created_at');
        $this->addSql('ALTER TABLE formas_retirada DROP updated_at');
        $this->addSql('ALTER TABLE formas_retirada ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE formas_retirada ALTER forma TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE logradouros DROP CONSTRAINT IF EXISTS logradouros_id_bairro_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_logradouros_cep');
        $this->addSql('ALTER TABLE logradouros ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE logradouros ALTER id_bairro TYPE INT USING id_bairro::integer');
        $this->addSql('ALTER TABLE logradouros ALTER cep TYPE VARCHAR(8)');
        $this->addSql('ALTER TABLE logradouros ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE logradouros ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE logradouros ADD CONSTRAINT FK_42E9C191A7C487E8 FOREIGN KEY (id_bairro) REFERENCES bairros (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS idx_logradouros_bairro RENAME TO IDX_42E9C191A7C487E8');
        $this->addSql('ALTER TABLE model_has_permissions DROP CONSTRAINT IF EXISTS model_has_permissions_permission_id_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_model_has_permissions_model');
        $this->addSql('DROP INDEX IF EXISTS IDX_6B22422AFED90CCA');
        $this->addSql('ALTER TABLE model_has_permissions DROP CONSTRAINT IF EXISTS model_has_permissions_pkey');
        $this->addSql('ALTER TABLE model_has_permissions ADD PRIMARY KEY (permission_id, model_type, model_id)');
        $this->addSql('ALTER TABLE model_has_roles DROP CONSTRAINT IF EXISTS model_has_roles_role_id_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_model_has_roles_model');
        $this->addSql('DROP INDEX IF EXISTS IDX_747E57EAD60322AC');
        $this->addSql('ALTER TABLE model_has_roles DROP CONSTRAINT IF EXISTS model_has_roles_pkey');
        $this->addSql('ALTER TABLE model_has_roles ADD PRIMARY KEY (role_id, model_type, model_id)');
        $this->addSql('ALTER TABLE permissions DROP created_at');
        $this->addSql('ALTER TABLE permissions DROP updated_at');
        $this->addSql('ALTER TABLE permissions ALTER id TYPE INT USING id::integer');
        $this->addSql('DROP INDEX IF EXISTS idx_personal_access_tokens_tokenable');
        $this->addSql('ALTER TABLE personal_access_tokens DROP created_at');
        $this->addSql('ALTER TABLE personal_access_tokens DROP updated_at');
        $this->addSql('ALTER TABLE personal_access_tokens ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE personal_access_tokens ALTER token TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT IF EXISTS fk_pessoas_user');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_dt_cadastro');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_fisica_juridica');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_status');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_tipo');
        $this->addSql('ALTER TABLE pessoas DROP created_at');
        $this->addSql('ALTER TABLE pessoas DROP updated_at');
        $this->addSql('ALTER TABLE pessoas ALTER idpessoa TYPE INT USING idpessoa::integer');
        $this->addSql('ALTER TABLE pessoas ALTER dt_cadastro DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas ALTER fisica_juridica TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas ALTER nome_pai TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas ALTER nome_mae TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas ALTER renda TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE pessoas ADD CONSTRAINT FK_18A4F2ACA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX IF EXISTS uniq_pessoa_user RENAME TO UNIQ_18A4F2ACA76ED395');
        $this->addSql('ALTER TABLE pessoas_contratantes DROP CONSTRAINT IF EXISTS pessoas_contratantes_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_contratantes ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_contratantes ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE pessoas_contratantes ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_contratantes ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_contratantes ADD CONSTRAINT FK_25184ED03AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_corretoras DROP CONSTRAINT IF EXISTS pessoas_corretoras_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_corretoras ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_corretoras ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE pessoas_corretoras ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_corretoras ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_corretoras ADD CONSTRAINT FK_80304A5F3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_corretores DROP CONSTRAINT IF EXISTS pessoas_corretores_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_corretores DROP created_at');
        $this->addSql('ALTER TABLE pessoas_corretores DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER creci TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER usuario TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER status TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_corretores ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_corretores ADD CONSTRAINT FK_E45C8F5B3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E45C8F5B3AE81E6F ON pessoas_corretores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_documentos DROP CONSTRAINT IF EXISTS pessoas_documentos_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_documentos DROP CONSTRAINT IF EXISTS pessoas_documentos_id_tipo_documento_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_documentos_numero');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_documentos_pessoa');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_documentos_tipo');
        $this->addSql('ALTER TABLE pessoas_documentos DROP created_at');
        $this->addSql('ALTER TABLE pessoas_documentos DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER numero_documento TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER orgao_emissor TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_emails DROP CONSTRAINT IF EXISTS pessoas_emails_id_email_fkey');
        $this->addSql('ALTER TABLE pessoas_emails DROP CONSTRAINT IF EXISTS pessoas_emails_id_pessoa_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_emails_email');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_emails_pessoa');
        $this->addSql('ALTER TABLE pessoas_emails DROP created_at');
        $this->addSql('ALTER TABLE pessoas_emails DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_emails ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_fiadores DROP CONSTRAINT IF EXISTS pessoas_fiadores_id_conjuge_fkey');
        $this->addSql('ALTER TABLE pessoas_fiadores DROP CONSTRAINT IF EXISTS pessoas_fiadores_id_pessoa_fkey');
        $this->addSql('DROP INDEX IF EXISTS IDX_EA5BC63A37CA81BE');
        $this->addSql('ALTER TABLE pessoas_fiadores DROP created_at');
        $this->addSql('ALTER TABLE pessoas_fiadores DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_fiadores ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_fiadores ALTER ja_foi_fiador DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_fiadores ALTER conjuge_trabalha DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores DROP CONSTRAINT IF EXISTS pessoas_locadores_id_forma_retirada_fkey');
        $this->addSql('ALTER TABLE pessoas_locadores DROP CONSTRAINT IF EXISTS pessoas_locadores_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_locadores DROP created_at');
        $this->addSql('ALTER TABLE pessoas_locadores DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER id_pessoa TYPE INT USING id_pessoa::integer');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER id_forma_retirada TYPE INT USING id_forma_retirada::integer');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER dependentes DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER cobrar_cpmf DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER situacao DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER etiqueta DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER cobrar_tarifa_rec DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER carencia DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER multa_itau DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER mora_diaria DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER protesto DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER dias_protesto DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER nao_gerar_judicial DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER endereco_cobranca DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER condominio_conta DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ALTER ext_email DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_locadores ADD CONSTRAINT FK_99A9F08D3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_locadores ADD CONSTRAINT FK_99A9F08DF1D3B3A1 FOREIGN KEY (id_forma_retirada) REFERENCES formas_retirada (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_99A9F08D3AE81E6F ON pessoas_locadores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_atendente_fkey');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_logradouro_desejado_fkey');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_tipo_atendimento_fkey');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT IF EXISTS pessoas_pretendentes_id_tipo_imovel_fkey');
        $this->addSql('DROP INDEX IF EXISTS IDX_B57CEF67BAC6B6DF');
        $this->addSql('DROP INDEX IF EXISTS IDX_B57CEF674D6C7D6D');
        $this->addSql('DROP INDEX IF EXISTS IDX_B57CEF67E90B7405');
        $this->addSql('DROP INDEX IF EXISTS IDX_B57CEF671D873604');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP created_at');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER aluguel_maximo TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER disponivel DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER procura_aluguel DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER procura_compra DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_profissoes DROP CONSTRAINT IF EXISTS pessoas_profissoes_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_profissoes DROP CONSTRAINT IF EXISTS pessoas_profissoes_id_profissao_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_profissoes_pessoa');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_profissoes_profissao');
        $this->addSql('ALTER TABLE pessoas_profissoes DROP created_at');
        $this->addSql('ALTER TABLE pessoas_profissoes DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_profissoes ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_profissoes ALTER empresa TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pessoas_profissoes ALTER renda TYPE NUMERIC(10, 0)');
        $this->addSql('ALTER TABLE pessoas_profissoes ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_telefones DROP CONSTRAINT IF EXISTS pessoas_telefones_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_telefones DROP CONSTRAINT IF EXISTS pessoas_telefones_id_telefone_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_telefones_pessoa');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_telefones_telefone');
        $this->addSql('ALTER TABLE pessoas_telefones DROP created_at');
        $this->addSql('ALTER TABLE pessoas_telefones DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_telefones ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_tipos DROP CONSTRAINT IF EXISTS pessoas_tipos_id_pessoa_fkey');
        $this->addSql('ALTER TABLE pessoas_tipos DROP CONSTRAINT IF EXISTS pessoas_tipos_id_tipo_pessoa_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_tipos_pessoa');
        $this->addSql('DROP INDEX IF EXISTS idx_pessoas_tipos_tipo');
        $this->addSql('ALTER TABLE pessoas_tipos DROP created_at');
        $this->addSql('ALTER TABLE pessoas_tipos DROP updated_at');
        $this->addSql('ALTER TABLE pessoas_tipos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE pessoas_tipos ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE profissoes DROP created_at');
        $this->addSql('ALTER TABLE profissoes DROP updated_at');
        $this->addSql('ALTER TABLE profissoes ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE profissoes ALTER nome TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE profissoes ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE razoes_conta DROP created_at');
        $this->addSql('ALTER TABLE razoes_conta DROP updated_at');
        $this->addSql('ALTER TABLE razoes_conta ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE razoes_conta ALTER razao TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP CONSTRAINT IF EXISTS relacionamentos_familiares_id_pessoa_destino_fkey');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP CONSTRAINT IF EXISTS relacionamentos_familiares_id_pessoa_origem_fkey');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP CONSTRAINT IF EXISTS relacionamentos_familiares_id_regime_casamento_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_relacionamentos_destino');
        $this->addSql('DROP INDEX IF EXISTS idx_relacionamentos_origem');
        $this->addSql('DROP INDEX IF EXISTS idx_relacionamentos_regime');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP created_at');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP updated_at');
        $this->addSql('ALTER TABLE relacionamentos_familiares ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE relacionamentos_familiares ALTER tipo_relacionamento TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE relacionamentos_familiares ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE requisicoes_responsaveis DROP CONSTRAINT IF EXISTS requisicoes_responsaveis_id_inquilino_fkey');
        $this->addSql('ALTER TABLE requisicoes_responsaveis DROP CONSTRAINT IF EXISTS requisicoes_responsaveis_id_pessoa_fkey');
        $this->addSql('DROP INDEX IF EXISTS idx_requisicoes_inquilino');
        $this->addSql('DROP INDEX IF EXISTS idx_requisicoes_numero');
        $this->addSql('DROP INDEX IF EXISTS idx_requisicoes_pessoa');
        $this->addSql('ALTER TABLE requisicoes_responsaveis DROP created_at');
        $this->addSql('ALTER TABLE requisicoes_responsaveis DROP updated_at');
        $this->addSql('ALTER TABLE requisicoes_responsaveis ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE roles DROP created_at');
        $this->addSql('ALTER TABLE roles DROP updated_at');
        $this->addSql('ALTER TABLE roles ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE sessions ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE sessions ALTER ip_address TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE telefones DROP created_at');
        $this->addSql('ALTER TABLE telefones DROP updated_at');
        $this->addSql('ALTER TABLE telefones ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE telefones ALTER id_tipo TYPE INT USING id_tipo::integer');
        $this->addSql('ALTER TABLE tipos_atendimento DROP created_at');
        $this->addSql('ALTER TABLE tipos_atendimento DROP updated_at');
        $this->addSql('ALTER TABLE tipos_atendimento ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_atendimento ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_carteiras DROP created_at');
        $this->addSql('ALTER TABLE tipos_carteiras DROP updated_at');
        $this->addSql('ALTER TABLE tipos_carteiras ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_carteiras ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_chaves_pix DROP created_at');
        $this->addSql('ALTER TABLE tipos_chaves_pix DROP updated_at');
        $this->addSql('ALTER TABLE tipos_chaves_pix ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_chaves_pix ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_contas_bancarias DROP created_at');
        $this->addSql('ALTER TABLE tipos_contas_bancarias DROP updated_at');
        $this->addSql('ALTER TABLE tipos_contas_bancarias ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_contas_bancarias ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_documentos DROP created_at');
        $this->addSql('ALTER TABLE tipos_documentos DROP updated_at');
        $this->addSql('ALTER TABLE tipos_documentos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_documentos ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_emails DROP created_at');
        $this->addSql('ALTER TABLE tipos_emails DROP updated_at');
        $this->addSql('ALTER TABLE tipos_emails ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_emails ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER created_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER updated_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER created_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER updated_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_pessoas DROP created_at');
        $this->addSql('ALTER TABLE tipos_pessoas DROP updated_at');
        $this->addSql('ALTER TABLE tipos_pessoas ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_pessoas ALTER tipo TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_pessoas ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_remessa DROP created_at');
        $this->addSql('ALTER TABLE tipos_remessa DROP updated_at');
        $this->addSql('ALTER TABLE tipos_remessa ALTER id TYPE INT USING id::integer');
        $this->addSql('ALTER TABLE tipos_remessa ALTER tipo TYPE VARCHAR(255)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->throwIrreversibleMigrationException('Esta migration é complexa e não pode ser revertida facilmente.');
    }
}

