<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251209005146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sincronização completa do schema - Remove sequences órfãs, normaliza índices e constraints para padrão Doctrine';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE seq_numero_acordo CASCADE');
        $this->addSql('DROP SEQUENCE seq_nosso_numero CASCADE');
        $this->addSql('DROP INDEX idx_acordo_situacao');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER data_acordo DROP DEFAULT');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER situacao DROP DEFAULT');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_acordo_inquilino RENAME TO IDX_FE2A920AC6CAFDDA');
        $this->addSql('DROP INDEX idx_baixa_data');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER forma_pagamento DROP DEFAULT');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER tipo_baixa DROP DEFAULT');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER estornada DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_baixa_lancamento RENAME TO IDX_B9529BBDC319336A');
        $this->addSql('ALTER INDEX idx_baixa_conta RENAME TO IDX_B9529BBD20B2308E');
        $this->addSql('DROP INDEX IF EXISTS idx_boletos_nosso_numero');
        $this->addSql('DROP INDEX idx_boletos_status');
        $this->addSql('DROP INDEX idx_boletos_vencimento');
        $this->addSql('ALTER TABLE boletos ALTER valor_desconto DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER valor_multa DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER valor_juros_dia DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER valor_abatimento DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER tipo_desconto DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER tipo_juros DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER tipo_multa DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER tentativas_registro DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE boletos ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_boletos_config RENAME TO IDX_504C35223011851E');
        $this->addSql('ALTER INDEX idx_boletos_lancamento RENAME TO IDX_504C3522E40F7CCC');
        $this->addSql('ALTER INDEX idx_boletos_pagador RENAME TO IDX_504C352284D16893');
        $this->addSql('ALTER INDEX idx_boletos_imovel RENAME TO IDX_504C35224480E84F');
        $this->addSql('DROP INDEX idx_boletos_log_created');
        $this->addSql('DROP INDEX idx_boletos_log_operacao');
        $this->addSql('ALTER TABLE boletos_log_api ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_boletos_log_boleto RENAME TO IDX_B729FAAB7F6F0A9B');
        $this->addSql('DROP INDEX idx_config_api_banco_ambiente');
        $this->addSql('ALTER TABLE configuracoes_api_banco DROP CONSTRAINT IF EXISTS idx_config_api_banco_unique');
        $this->addSql('DROP INDEX IF EXISTS idx_config_api_banco_unique');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER carteira DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER ambiente DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_config_api_banco_banco RENAME TO IDX_F580B186CC04A73E');
        $this->addSql('ALTER INDEX idx_config_api_banco_conta RENAME TO IDX_F580B18686F47FDE');
        $this->addSql('DROP INDEX idx_cobrancas_boleto');
        $this->addSql('DROP INDEX idx_cobrancas_competencia');
        $this->addSql('DROP INDEX idx_cobrancas_status');
        $this->addSql('DROP INDEX idx_cobrancas_vencimento');
        $this->addSql('ALTER TABLE contratos_cobrancas DROP CONSTRAINT IF EXISTS uk_cobranca_contrato_competencia');
        $this->addSql('COMMENT ON COLUMN contratos_cobrancas.competencia IS NULL');
        $this->addSql('COMMENT ON COLUMN contratos_cobrancas.bloqueado_rotina_auto IS NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C9ACF5E7F6F0A9B ON contratos_cobrancas (boleto_id)');
        $this->addSql('ALTER INDEX idx_cobrancas_contrato RENAME TO IDX_3C9ACF5E70AE7BF1');
        $this->addSql('DROP INDEX idx_contratos_itens_ativo');
        $this->addSql('DROP INDEX idx_contratos_itens_tipo');
        $this->addSql('ALTER TABLE contratos_itens_cobranca DROP CONSTRAINT IF EXISTS uk_itens_contrato_tipo');
        $this->addSql('ALTER INDEX idx_contratos_itens_contrato RENAME TO IDX_9D5C33170AE7BF1');
        $this->addSql('DROP INDEX idx_emails_destinatario');
        $this->addSql('DROP INDEX idx_emails_enviado_em');
        $this->addSql('DROP INDEX idx_emails_status');
        $this->addSql('DROP INDEX idx_emails_tipo');
        $this->addSql('DROP INDEX idx_contratos_ativo');
        $this->addSql('DROP INDEX idx_contratos_data_fim');
        $this->addSql('DROP INDEX idx_contratos_data_proximo_reajuste');
        $this->addSql('DROP INDEX idx_contratos_status');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_boleto');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_conta_bancaria');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_contrato');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_created_by');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_pessoa_credor');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT fk_lancamentos_pessoa_pagador');
        $this->addSql('DROP INDEX idx_lancamentos_competencia');
        $this->addSql('DROP INDEX idx_lancamentos_status');
        $this->addSql('DROP INDEX idx_lancamentos_tipo');
        $this->addSql('DROP INDEX idx_lancamentos_vencimento');
        $this->addSql('ALTER TABLE lancamentos ALTER tipo DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_pago DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_desconto DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_juros DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_multa DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER reter_inss DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER reter_iss DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ALTER origem DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB8938999DB40F2 FOREIGN KEY (id_pessoa_credor) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB8938952706124 FOREIGN KEY (id_pessoa_pagador) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB8938936B289B6 FOREIGN KEY (id_contrato) REFERENCES imoveis_contratos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB8938920B2308E FOREIGN KEY (id_conta_bancaria) REFERENCES contas_bancarias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB893896019DBC8 FOREIGN KEY (id_boleto) REFERENCES boletos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT FK_AEB89389DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_lancamentos_pessoa_credor RENAME TO IDX_AEB8938999DB40F2');
        $this->addSql('ALTER INDEX idx_lancamentos_pessoa_pagador RENAME TO IDX_AEB8938952706124');
        $this->addSql('ALTER INDEX idx_lancamentos_contrato RENAME TO IDX_AEB8938936B289B6');
        $this->addSql('DROP INDEX idx_lanc_competencia');
        $this->addSql('DROP INDEX idx_lanc_situacao');
        $this->addSql('DROP INDEX idx_lanc_vencimento');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER numero_parcela DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER data_lancamento DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER situacao DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER tipo_lancamento DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER origem DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER gerado_automaticamente DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER enviado_email DROP DEFAULT');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER impresso DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_lanc_contrato RENAME TO IDX_1A9C3B7F36B289B6');
        $this->addSql('ALTER INDEX idx_lanc_imovel RENAME TO IDX_1A9C3B7FB61BB806');
        $this->addSql('ALTER INDEX idx_lanc_inquilino RENAME TO IDX_1A9C3B7FC6CAFDDA');
        $this->addSql('ALTER INDEX idx_lanc_proprietario RENAME TO IDX_1A9C3B7F13B282B1');
        $this->addSql('ALTER TABLE pessoas_advogados DROP CONSTRAINT fk_advogados_pessoa');
        $this->addSql('DROP INDEX idx_pessoas_advogados_ativo');
        $this->addSql('DROP INDEX idx_pessoas_advogados_oab');
        $this->addSql('DROP INDEX idx_pessoas_advogados_pessoa');
        $this->addSql('ALTER TABLE pessoas_advogados DROP CONSTRAINT IF EXISTS uk_advogados_pessoa');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_socios DROP CONSTRAINT fk_socios_pessoa');
        $this->addSql('DROP INDEX idx_pessoas_socios_ativo');
        $this->addSql('DROP INDEX idx_pessoas_socios_pessoa');
        $this->addSql('ALTER TABLE pessoas_socios DROP CONSTRAINT IF EXISTS uk_socios_pessoa');
        $this->addSql('ALTER TABLE pessoas_socios ALTER ativo DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_socios ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_socios ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT fk_prestacao_conta_bancaria');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT fk_prestacao_created_by');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT fk_prestacao_imovel');
        $this->addSql('DROP INDEX idx_prestacoes_contas_ano');
        $this->addSql('DROP INDEX idx_prestacoes_contas_periodo');
        $this->addSql('DROP INDEX idx_prestacoes_contas_status');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT IF EXISTS uk_prestacao_numero_ano');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER tipo_periodo DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER incluir_ficha_financeira DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER incluir_lancamentos DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_receitas DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_despesas DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_taxa_admin DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_retencao_ir DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER valor_repasse DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT FK_7B153181B61BB806 FOREIGN KEY (id_imovel) REFERENCES imoveis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT FK_7B15318120B2308E FOREIGN KEY (id_conta_bancaria) REFERENCES contas_bancarias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT FK_7B153181DE12AB56 FOREIGN KEY (created_by) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_prestacoes_contas_proprietario RENAME TO IDX_7B15318113B282B1');
        $this->addSql('ALTER INDEX idx_prestacoes_contas_imovel RENAME TO IDX_7B153181B61BB806');
        $this->addSql('DROP INDEX idx_prestacoes_itens_tipo');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER valor_taxa_admin DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER valor_retencao_ir DROP DEFAULT');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_prestacoes_itens_prestacao RENAME TO IDX_36C5204574F763E9');
        $this->addSql('ALTER INDEX idx_prestacoes_itens_imovel RENAME TO IDX_36C52045B61BB806');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('CREATE SEQUENCE seq_numero_acordo INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE seq_nosso_numero INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB8938999DB40F2');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB8938952706124');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB8938936B289B6');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB8938920B2308E');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB893896019DBC8');
        $this->addSql('ALTER TABLE lancamentos DROP CONSTRAINT FK_AEB89389DE12AB56');
        $this->addSql('ALTER TABLE lancamentos ALTER tipo SET DEFAULT \'receber\'');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_pago SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_desconto SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_juros SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE lancamentos ALTER valor_multa SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE lancamentos ALTER reter_inss SET DEFAULT false');
        $this->addSql('ALTER TABLE lancamentos ALTER reter_iss SET DEFAULT false');
        $this->addSql('ALTER TABLE lancamentos ALTER status SET DEFAULT \'aberto\'');
        $this->addSql('ALTER TABLE lancamentos ALTER origem SET DEFAULT \'manual\'');
        $this->addSql('ALTER TABLE lancamentos ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE lancamentos ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_boleto FOREIGN KEY (id_boleto) REFERENCES boletos (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_conta_bancaria FOREIGN KEY (id_conta_bancaria) REFERENCES contas_bancarias (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_contrato FOREIGN KEY (id_contrato) REFERENCES imoveis_contratos (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_pessoa_credor FOREIGN KEY (id_pessoa_credor) REFERENCES pessoas (idpessoa) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE lancamentos ADD CONSTRAINT fk_lancamentos_pessoa_pagador FOREIGN KEY (id_pessoa_pagador) REFERENCES pessoas (idpessoa) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_lancamentos_competencia ON lancamentos (competencia)');
        $this->addSql('CREATE INDEX idx_lancamentos_status ON lancamentos (status)');
        $this->addSql('CREATE INDEX idx_lancamentos_tipo ON lancamentos (tipo)');
        $this->addSql('CREATE INDEX idx_lancamentos_vencimento ON lancamentos (data_vencimento)');
        $this->addSql('ALTER INDEX idx_aeb8938936b289b6 RENAME TO idx_lancamentos_contrato');
        $this->addSql('ALTER INDEX idx_aeb8938999db40f2 RENAME TO idx_lancamentos_pessoa_credor');
        $this->addSql('ALTER INDEX idx_aeb8938952706124 RENAME TO idx_lancamentos_pessoa_pagador');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER valor_taxa_admin SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER valor_retencao_ir SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas_itens ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_prestacoes_itens_tipo ON prestacoes_contas_itens (tipo)');
        $this->addSql('ALTER INDEX idx_36c52045b61bb806 RENAME TO idx_prestacoes_itens_imovel');
        $this->addSql('ALTER INDEX idx_36c5204574f763e9 RENAME TO idx_prestacoes_itens_prestacao');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT FK_7B153181B61BB806');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT FK_7B15318120B2308E');
        $this->addSql('ALTER TABLE prestacoes_contas DROP CONSTRAINT FK_7B153181DE12AB56');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER tipo_periodo SET DEFAULT \'mensal\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER incluir_ficha_financeira SET DEFAULT true');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER incluir_lancamentos SET DEFAULT true');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_receitas SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_despesas SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_taxa_admin SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER total_retencao_ir SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER valor_repasse SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER status SET DEFAULT \'gerado\'');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE prestacoes_contas ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT fk_prestacao_conta_bancaria FOREIGN KEY (id_conta_bancaria) REFERENCES contas_bancarias (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT fk_prestacao_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestacoes_contas ADD CONSTRAINT fk_prestacao_imovel FOREIGN KEY (id_imovel) REFERENCES imoveis (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_prestacoes_contas_ano ON prestacoes_contas (ano)');
        $this->addSql('CREATE INDEX idx_prestacoes_contas_periodo ON prestacoes_contas (data_inicio, data_fim)');
        $this->addSql('CREATE INDEX idx_prestacoes_contas_status ON prestacoes_contas (status)');
        $this->addSql('CREATE UNIQUE INDEX uk_prestacao_numero_ano ON prestacoes_contas (numero, ano)');
        $this->addSql('ALTER INDEX idx_7b153181b61bb806 RENAME TO idx_prestacoes_contas_imovel');
        $this->addSql('ALTER INDEX idx_7b15318113b282b1 RENAME TO idx_prestacoes_contas_proprietario');
        $this->addSql('DROP INDEX UNIQ_3C9ACF5E7F6F0A9B');
        $this->addSql('COMMENT ON COLUMN contratos_cobrancas.competencia IS \'Formato YYYY-MM, ex: 2025-12\'');
        $this->addSql('COMMENT ON COLUMN contratos_cobrancas.bloqueado_rotina_auto IS \'Se true, não será processado pela rotina automática\'');
        $this->addSql('CREATE INDEX idx_cobrancas_boleto ON contratos_cobrancas (boleto_id)');
        $this->addSql('CREATE INDEX idx_cobrancas_competencia ON contratos_cobrancas (competencia)');
        $this->addSql('CREATE INDEX idx_cobrancas_status ON contratos_cobrancas (status)');
        $this->addSql('CREATE INDEX idx_cobrancas_vencimento ON contratos_cobrancas (data_vencimento)');
        $this->addSql('CREATE UNIQUE INDEX uk_cobranca_contrato_competencia ON contratos_cobrancas (contrato_id, competencia)');
        $this->addSql('ALTER INDEX idx_3c9acf5e70ae7bf1 RENAME TO idx_cobrancas_contrato');
        $this->addSql('CREATE INDEX idx_contratos_itens_ativo ON contratos_itens_cobranca (ativo)');
        $this->addSql('CREATE INDEX idx_contratos_itens_tipo ON contratos_itens_cobranca (tipo_item)');
        $this->addSql('CREATE UNIQUE INDEX uk_itens_contrato_tipo ON contratos_itens_cobranca (contrato_id, tipo_item)');
        $this->addSql('ALTER INDEX idx_9d5c33170ae7bf1 RENAME TO idx_contratos_itens_contrato');
        $this->addSql('ALTER TABLE boletos_log_api ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_boletos_log_created ON boletos_log_api (created_at)');
        $this->addSql('CREATE INDEX idx_boletos_log_operacao ON boletos_log_api (operacao)');
        $this->addSql('ALTER INDEX idx_b729faab7f6f0a9b RENAME TO idx_boletos_log_boleto');
        $this->addSql('CREATE INDEX idx_emails_destinatario ON emails_enviados (destinatario)');
        $this->addSql('CREATE INDEX idx_emails_enviado_em ON emails_enviados (enviado_em)');
        $this->addSql('CREATE INDEX idx_emails_status ON emails_enviados (status)');
        $this->addSql('CREATE INDEX idx_emails_tipo ON emails_enviados (tipo_referencia, referencia_id)');
        $this->addSql('ALTER TABLE pessoas_socios ALTER ativo SET DEFAULT true');
        $this->addSql('ALTER TABLE pessoas_socios ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE pessoas_socios ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE pessoas_socios ADD CONSTRAINT fk_socios_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_pessoas_socios_ativo ON pessoas_socios (ativo)');
        $this->addSql('CREATE INDEX idx_pessoas_socios_pessoa ON pessoas_socios (id_pessoa)');
        $this->addSql('CREATE UNIQUE INDEX uk_socios_pessoa ON pessoas_socios (id_pessoa)');
        $this->addSql('ALTER TABLE boletos ALTER valor_desconto SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE boletos ALTER valor_multa SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE boletos ALTER valor_juros_dia SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE boletos ALTER valor_abatimento SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE boletos ALTER tipo_desconto SET DEFAULT \'ISENTO\'');
        $this->addSql('ALTER TABLE boletos ALTER tipo_juros SET DEFAULT \'ISENTO\'');
        $this->addSql('ALTER TABLE boletos ALTER tipo_multa SET DEFAULT \'ISENTO\'');
        $this->addSql('ALTER TABLE boletos ALTER tentativas_registro SET DEFAULT 0');
        $this->addSql('ALTER TABLE boletos ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE boletos ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE UNIQUE INDEX idx_boletos_nosso_numero ON boletos (configuracao_api_id, nosso_numero)');
        $this->addSql('CREATE INDEX idx_boletos_status ON boletos (status)');
        $this->addSql('CREATE INDEX idx_boletos_vencimento ON boletos (data_vencimento)');
        $this->addSql('ALTER INDEX idx_504c35223011851e RENAME TO idx_boletos_config');
        $this->addSql('ALTER INDEX idx_504c35224480e84f RENAME TO idx_boletos_imovel');
        $this->addSql('ALTER INDEX idx_504c3522e40f7ccc RENAME TO idx_boletos_lancamento');
        $this->addSql('ALTER INDEX idx_504c352284d16893 RENAME TO idx_boletos_pagador');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER carteira SET DEFAULT \'101\'');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER ambiente SET DEFAULT \'sandbox\'');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER ativo SET DEFAULT true');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE configuracoes_api_banco ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_config_api_banco_ambiente ON configuracoes_api_banco (ambiente)');
        $this->addSql('CREATE UNIQUE INDEX idx_config_api_banco_unique ON configuracoes_api_banco (conta_bancaria_id, ambiente)');
        $this->addSql('ALTER INDEX idx_f580b186cc04a73e RENAME TO idx_config_api_banco_banco');
        $this->addSql('ALTER INDEX idx_f580b18686f47fde RENAME TO idx_config_api_banco_conta');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER data_acordo SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER situacao SET DEFAULT \'ativo\'');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE acordos_financeiros ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('CREATE INDEX idx_acordo_situacao ON acordos_financeiros (situacao)');
        $this->addSql('ALTER INDEX idx_fe2a920ac6cafdda RENAME TO idx_acordo_inquilino');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER ativo SET DEFAULT true');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE pessoas_advogados ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE pessoas_advogados ADD CONSTRAINT fk_advogados_pessoa FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_pessoas_advogados_ativo ON pessoas_advogados (ativo)');
        $this->addSql('CREATE INDEX idx_pessoas_advogados_oab ON pessoas_advogados (numero_oab)');
        $this->addSql('CREATE INDEX idx_pessoas_advogados_pessoa ON pessoas_advogados (id_pessoa)');
        $this->addSql('CREATE UNIQUE INDEX uk_advogados_pessoa ON pessoas_advogados (id_pessoa)');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER forma_pagamento SET DEFAULT \'boleto\'');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER tipo_baixa SET DEFAULT \'normal\'');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE baixas_financeiras ALTER estornada SET DEFAULT false');
        $this->addSql('CREATE INDEX idx_baixa_data ON baixas_financeiras (data_pagamento)');
        $this->addSql('ALTER INDEX idx_b9529bbd20b2308e RENAME TO idx_baixa_conta');
        $this->addSql('ALTER INDEX idx_b9529bbdc319336a RENAME TO idx_baixa_lancamento');
        $this->addSql('CREATE INDEX idx_contratos_ativo ON imoveis_contratos (ativo)');
        $this->addSql('CREATE INDEX idx_contratos_data_fim ON imoveis_contratos (data_fim)');
        $this->addSql('CREATE INDEX idx_contratos_data_proximo_reajuste ON imoveis_contratos (data_proximo_reajuste)');
        $this->addSql('CREATE INDEX idx_contratos_status ON imoveis_contratos (status)');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER numero_parcela SET DEFAULT 1');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER data_lancamento SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER situacao SET DEFAULT \'aberto\'');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER tipo_lancamento SET DEFAULT \'aluguel\'');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER origem SET DEFAULT \'contrato\'');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER gerado_automaticamente SET DEFAULT false');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER ativo SET DEFAULT true');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER enviado_email SET DEFAULT false');
        $this->addSql('ALTER TABLE lancamentos_financeiros ALTER impresso SET DEFAULT false');
        $this->addSql('CREATE INDEX idx_lanc_competencia ON lancamentos_financeiros (competencia)');
        $this->addSql('CREATE INDEX idx_lanc_situacao ON lancamentos_financeiros (situacao)');
        $this->addSql('CREATE INDEX idx_lanc_vencimento ON lancamentos_financeiros (data_vencimento)');
        $this->addSql('ALTER INDEX idx_1a9c3b7f36b289b6 RENAME TO idx_lanc_contrato');
        $this->addSql('ALTER INDEX idx_1a9c3b7fb61bb806 RENAME TO idx_lanc_imovel');
        $this->addSql('ALTER INDEX idx_1a9c3b7fc6cafdda RENAME TO idx_lanc_inquilino');
        $this->addSql('ALTER INDEX idx_1a9c3b7f13b282b1 RENAME TO idx_lanc_proprietario');
    }
}
