<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251129221123 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE agencias_id_seq');
        $this->addSql('SELECT setval(\'agencias_id_seq\', (SELECT MAX(id) FROM agencias))');
        $this->addSql('ALTER TABLE agencias ALTER id SET DEFAULT nextval(\'agencias_id_seq\')');
        $this->addSql('ALTER TABLE agencias ADD CONSTRAINT FK_923688C0995BA0E1 FOREIGN KEY (id_banco) REFERENCES bancos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agencias ADD CONSTRAINT FK_923688C0A83B3A9B FOREIGN KEY (id_endereco) REFERENCES enderecos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_923688C0995BA0E1 ON agencias (id_banco)');
        $this->addSql('CREATE INDEX IDX_923688C0A83B3A9B ON agencias (id_endereco)');
        $this->addSql('ALTER TABLE agencias ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE bairros_id_seq');
        $this->addSql('SELECT setval(\'bairros_id_seq\', (SELECT MAX(id) FROM bairros))');
        $this->addSql('ALTER TABLE bairros ALTER id SET DEFAULT nextval(\'bairros_id_seq\')');
        $this->addSql('ALTER TABLE bairros ADD CONSTRAINT FK_6BE5C8B64CAF86B1 FOREIGN KEY (id_cidade) REFERENCES cidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_6BE5C8B64CAF86B1 ON bairros (id_cidade)');
        $this->addSql('ALTER TABLE bairros ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE bancos_id_seq');
        $this->addSql('SELECT setval(\'bancos_id_seq\', (SELECT MAX(id) FROM bancos))');
        $this->addSql('ALTER TABLE bancos ALTER id SET DEFAULT nextval(\'bancos_id_seq\')');
        $this->addSql('ALTER TABLE bancos ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE chaves_pix ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE cidades_id_seq');
        $this->addSql('SELECT setval(\'cidades_id_seq\', (SELECT MAX(id) FROM cidades))');
        $this->addSql('ALTER TABLE cidades ALTER id SET DEFAULT nextval(\'cidades_id_seq\')');
        $this->addSql('ALTER TABLE cidades ADD CONSTRAINT FK_79B94AE76A540E FOREIGN KEY (id_estado) REFERENCES estados (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_79B94AE76A540E ON cidades (id_estado)');
        $this->addSql('ALTER TABLE cidades ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE configuracoes_cobranca_id_seq');
        $this->addSql('SELECT setval(\'configuracoes_cobranca_id_seq\', (SELECT MAX(id) FROM configuracoes_cobranca))');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER id SET DEFAULT nextval(\'configuracoes_cobranca_id_seq\')');
        $this->addSql('ALTER TABLE configuracoes_cobranca ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE contas_bancarias_id_seq');
        $this->addSql('SELECT setval(\'contas_bancarias_id_seq\', (SELECT MAX(id) FROM contas_bancarias))');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id SET DEFAULT nextval(\'contas_bancarias_id_seq\')');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDB3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDB995BA0E1 FOREIGN KEY (id_banco) REFERENCES bancos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDB35F182E9 FOREIGN KEY (id_agencia) REFERENCES agencias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contas_bancarias ADD CONSTRAINT FK_E7120EDBEB6C0CDC FOREIGN KEY (id_tipo_conta) REFERENCES tipos_contas_bancarias (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E7120EDB3AE81E6F ON contas_bancarias (id_pessoa)');
        $this->addSql('CREATE INDEX IDX_E7120EDB995BA0E1 ON contas_bancarias (id_banco)');
        $this->addSql('CREATE INDEX IDX_E7120EDB35F182E9 ON contas_bancarias (id_agencia)');
        $this->addSql('CREATE INDEX IDX_E7120EDBEB6C0CDC ON contas_bancarias (id_tipo_conta)');
        $this->addSql('ALTER TABLE contas_bancarias ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE contas_vinculadas_id_seq');
        $this->addSql('SELECT setval(\'contas_vinculadas_id_seq\', (SELECT MAX(id) FROM contas_vinculadas))');
        $this->addSql('ALTER TABLE contas_vinculadas ALTER id SET DEFAULT nextval(\'contas_vinculadas_id_seq\')');
        $this->addSql('ALTER TABLE contas_vinculadas ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE emails ADD CONSTRAINT FK_4C81E852FB0D0145 FOREIGN KEY (id_tipo) REFERENCES tipos_emails (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_4C81E852FB0D0145 ON emails (id_tipo)');
        $this->addSql('ALTER TABLE emails ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DA3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DAF1B90DAB FOREIGN KEY (id_logradouro) REFERENCES logradouros (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE enderecos ADD CONSTRAINT FK_FC4E02DAFB0D0145 FOREIGN KEY (id_tipo) REFERENCES tipos_enderecos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_FC4E02DA3AE81E6F ON enderecos (id_pessoa)');
        $this->addSql('CREATE INDEX IDX_FC4E02DAF1B90DAB ON enderecos (id_logradouro)');
        $this->addSql('CREATE INDEX IDX_FC4E02DAFB0D0145 ON enderecos (id_tipo)');
        $this->addSql('ALTER TABLE enderecos ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE estado_civil_id_seq');
        $this->addSql('SELECT setval(\'estado_civil_id_seq\', (SELECT MAX(id) FROM estado_civil))');
        $this->addSql('ALTER TABLE estado_civil ALTER id SET DEFAULT nextval(\'estado_civil_id_seq\')');
        $this->addSql('ALTER TABLE estado_civil ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE estados_id_seq');
        $this->addSql('SELECT setval(\'estados_id_seq\', (SELECT MAX(id) FROM estados))');
        $this->addSql('ALTER TABLE estados ALTER id SET DEFAULT nextval(\'estados_id_seq\')');
        $this->addSql('ALTER TABLE estados ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE failed_jobs_id_seq');
        $this->addSql('SELECT setval(\'failed_jobs_id_seq\', (SELECT MAX(id) FROM failed_jobs))');
        $this->addSql('ALTER TABLE failed_jobs ALTER id SET DEFAULT nextval(\'failed_jobs_id_seq\')');
        $this->addSql('ALTER TABLE failed_jobs ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP data_inicio');
        $this->addSql('CREATE SEQUENCE fiadores_inquilinos_id_seq');
        $this->addSql('SELECT setval(\'fiadores_inquilinos_id_seq\', (SELECT MAX(id) FROM fiadores_inquilinos))');
        $this->addSql('ALTER TABLE fiadores_inquilinos ALTER id SET DEFAULT nextval(\'fiadores_inquilinos_id_seq\')');
        $this->addSql('ALTER TABLE fiadores_inquilinos ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE formas_retirada_id_seq');
        $this->addSql('SELECT setval(\'formas_retirada_id_seq\', (SELECT MAX(id) FROM formas_retirada))');
        $this->addSql('ALTER TABLE formas_retirada ALTER id SET DEFAULT nextval(\'formas_retirada_id_seq\')');
        $this->addSql('ALTER TABLE formas_retirada ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE layouts_remessa_id_seq');
        $this->addSql('SELECT setval(\'layouts_remessa_id_seq\', (SELECT MAX(id) FROM layouts_remessa))');
        $this->addSql('ALTER TABLE layouts_remessa ALTER id SET DEFAULT nextval(\'layouts_remessa_id_seq\')');
        $this->addSql('ALTER TABLE layouts_remessa ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE logradouros_id_seq');
        $this->addSql('SELECT setval(\'logradouros_id_seq\', (SELECT MAX(id) FROM logradouros))');
        $this->addSql('ALTER TABLE logradouros ALTER id SET DEFAULT nextval(\'logradouros_id_seq\')');
        $this->addSql('ALTER TABLE logradouros ADD CONSTRAINT FK_42E9C191A7C487E8 FOREIGN KEY (id_bairro) REFERENCES bairros (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_42E9C191A7C487E8 ON logradouros (id_bairro)');
        $this->addSql('ALTER TABLE logradouros ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE model_has_permissions ADD PRIMARY KEY (permission_id, model_type, model_id)');
        $this->addSql('ALTER TABLE model_has_roles ADD PRIMARY KEY (role_id, model_type, model_id)');
        $this->addSql('ALTER TABLE nacionalidades ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE naturalidades ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD PRIMARY KEY (email)');
        $this->addSql('CREATE SEQUENCE permissions_id_seq');
        $this->addSql('SELECT setval(\'permissions_id_seq\', (SELECT MAX(id) FROM permissions))');
        $this->addSql('ALTER TABLE permissions ALTER id SET DEFAULT nextval(\'permissions_id_seq\')');
        $this->addSql('ALTER TABLE permissions ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE personal_access_tokens_id_seq');
        $this->addSql('SELECT setval(\'personal_access_tokens_id_seq\', (SELECT MAX(id) FROM personal_access_tokens))');
        $this->addSql('ALTER TABLE personal_access_tokens ALTER id SET DEFAULT nextval(\'personal_access_tokens_id_seq\')');
        $this->addSql('ALTER TABLE personal_access_tokens ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE pessoas ADD CONSTRAINT FK_18A4F2AC75376D93 FOREIGN KEY (estado_civil_id) REFERENCES estado_civil (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas ADD CONSTRAINT FK_18A4F2AC21CE4288 FOREIGN KEY (nacionalidade_id) REFERENCES nacionalidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas ADD CONSTRAINT FK_18A4F2AC76BE313 FOREIGN KEY (naturalidade_id) REFERENCES naturalidades (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas ADD CONSTRAINT FK_18A4F2ACA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_18A4F2AC75376D93 ON pessoas (estado_civil_id)');
        $this->addSql('CREATE INDEX IDX_18A4F2AC21CE4288 ON pessoas (nacionalidade_id)');
        $this->addSql('CREATE INDEX IDX_18A4F2AC76BE313 ON pessoas (naturalidade_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_18A4F2ACA76ED395 ON pessoas (user_id)');
        $this->addSql('ALTER TABLE pessoas ADD PRIMARY KEY (idpessoa)');
        $this->addSql('ALTER TABLE pessoas_contratantes ADD CONSTRAINT FK_25184ED03AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_contratantes ADD PRIMARY KEY (id)');
        $this->addSql('ALTER INDEX uniq_pessoas_contratantes_id_pessoa RENAME TO UNIQ_25184ED03AE81E6F');
        $this->addSql('ALTER TABLE pessoas_corretoras ADD CONSTRAINT FK_80304A5F3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80304A5F3AE81E6F ON pessoas_corretoras (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_corretoras ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX uniq_pessoas_corretores_id_pessoa');
        $this->addSql('ALTER TABLE pessoas_corretores ADD CONSTRAINT FK_E45C8F5B3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_E45C8F5B3AE81E6F ON pessoas_corretores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_corretores ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX uniq_pessoas_documentos_pessoa_tipo_numero');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_pessoa TYPE INT');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_pessoa DROP NOT NULL');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_tipo_documento TYPE INT');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_tipo_documento DROP NOT NULL');
        $this->addSql('ALTER TABLE pessoas_documentos ADD CONSTRAINT FK_843B541B3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_documentos ADD CONSTRAINT FK_843B541B69B92C8F FOREIGN KEY (id_tipo_documento) REFERENCES tipos_documentos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_843B541B3AE81E6F ON pessoas_documentos (id_pessoa)');
        $this->addSql('CREATE INDEX IDX_843B541B69B92C8F ON pessoas_documentos (id_tipo_documento)');
        $this->addSql('ALTER TABLE pessoas_documentos ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE pessoas_emails ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX uniq_pessoas_fiadores_id_pessoa');
        $this->addSql('ALTER TABLE pessoas_fiadores ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX uniq_pessoas_locadores_id_pessoa');
        $this->addSql('ALTER TABLE pessoas_locadores ADD CONSTRAINT FK_99A9F08D3AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_locadores ADD CONSTRAINT FK_99A9F08DF1D3B3A1 FOREIGN KEY (id_forma_retirada) REFERENCES formas_retirada (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_99A9F08D3AE81E6F ON pessoas_locadores (id_pessoa)');
        $this->addSql('CREATE INDEX IDX_99A9F08DF1D3B3A1 ON pessoas_locadores (id_forma_retirada)');
        $this->addSql('ALTER TABLE pessoas_locadores ADD PRIMARY KEY (id)');
        $this->addSql('DROP INDEX uniq_pessoas_pretendentes_id_pessoa');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_pessoa TYPE INT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_tipo_imovel TYPE INT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER aluguel_maximo TYPE NUMERIC(10, 2)');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_logradouro_desejado TYPE INT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_atendente TYPE INT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_tipo_atendimento TYPE INT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD CONSTRAINT FK_B57CEF673AE81E6F FOREIGN KEY (id_pessoa) REFERENCES pessoas (idpessoa) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD CONSTRAINT FK_B57CEF671D873604 FOREIGN KEY (id_tipo_imovel) REFERENCES tipos_imoveis (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD CONSTRAINT FK_B57CEF674D6C7D6D FOREIGN KEY (id_logradouro_desejado) REFERENCES logradouros (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD CONSTRAINT FK_B57CEF67BAC6B6DF FOREIGN KEY (id_atendente) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD CONSTRAINT FK_B57CEF67E90B7405 FOREIGN KEY (id_tipo_atendimento) REFERENCES tipos_atendimento (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_B57CEF673AE81E6F ON pessoas_pretendentes (id_pessoa)');
        $this->addSql('CREATE INDEX IDX_B57CEF671D873604 ON pessoas_pretendentes (id_tipo_imovel)');
        $this->addSql('CREATE INDEX IDX_B57CEF674D6C7D6D ON pessoas_pretendentes (id_logradouro_desejado)');
        $this->addSql('CREATE INDEX IDX_B57CEF67BAC6B6DF ON pessoas_pretendentes (id_atendente)');
        $this->addSql('CREATE INDEX IDX_B57CEF67E90B7405 ON pessoas_pretendentes (id_tipo_atendimento)');
        $this->addSql('ALTER TABLE pessoas_pretendentes ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE pessoas_telefones ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE pessoas_tipos ALTER data_inicio DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_tipos ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE profissoes ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE razoes_conta_id_seq');
        $this->addSql('SELECT setval(\'razoes_conta_id_seq\', (SELECT MAX(id) FROM razoes_conta))');
        $this->addSql('ALTER TABLE razoes_conta ALTER id SET DEFAULT nextval(\'razoes_conta_id_seq\')');
        $this->addSql('ALTER TABLE razoes_conta ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE regimes_casamento_id_seq');
        $this->addSql('SELECT setval(\'regimes_casamento_id_seq\', (SELECT MAX(id) FROM regimes_casamento))');
        $this->addSql('ALTER TABLE regimes_casamento ALTER id SET DEFAULT nextval(\'regimes_casamento_id_seq\')');
        $this->addSql('ALTER TABLE regimes_casamento ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE relacionamentos_familiares ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE requisicoes_responsaveis_id_seq');
        $this->addSql('SELECT setval(\'requisicoes_responsaveis_id_seq\', (SELECT MAX(id) FROM requisicoes_responsaveis))');
        $this->addSql('ALTER TABLE requisicoes_responsaveis ALTER id SET DEFAULT nextval(\'requisicoes_responsaveis_id_seq\')');
        $this->addSql('ALTER TABLE requisicoes_responsaveis ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE role_has_permissions ADD PRIMARY KEY (permission_id, role_id)');
        $this->addSql('CREATE SEQUENCE roles_id_seq');
        $this->addSql('SELECT setval(\'roles_id_seq\', (SELECT MAX(id) FROM roles))');
        $this->addSql('ALTER TABLE roles ALTER id SET DEFAULT nextval(\'roles_id_seq\')');
        $this->addSql('ALTER TABLE roles ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE sessions ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE telefones ADD CONSTRAINT FK_219AAC26FB0D0145 FOREIGN KEY (id_tipo) REFERENCES tipos_telefones (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_219AAC26FB0D0145 ON telefones (id_tipo)');
        $this->addSql('ALTER TABLE telefones ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_atendimento_id_seq');
        $this->addSql('SELECT setval(\'tipos_atendimento_id_seq\', (SELECT MAX(id) FROM tipos_atendimento))');
        $this->addSql('ALTER TABLE tipos_atendimento ALTER id SET DEFAULT nextval(\'tipos_atendimento_id_seq\')');
        $this->addSql('ALTER TABLE tipos_atendimento ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_carteiras_id_seq');
        $this->addSql('SELECT setval(\'tipos_carteiras_id_seq\', (SELECT MAX(id) FROM tipos_carteiras))');
        $this->addSql('ALTER TABLE tipos_carteiras ALTER id SET DEFAULT nextval(\'tipos_carteiras_id_seq\')');
        $this->addSql('ALTER TABLE tipos_carteiras ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_chaves_pix_id_seq');
        $this->addSql('SELECT setval(\'tipos_chaves_pix_id_seq\', (SELECT MAX(id) FROM tipos_chaves_pix))');
        $this->addSql('ALTER TABLE tipos_chaves_pix ALTER id SET DEFAULT nextval(\'tipos_chaves_pix_id_seq\')');
        $this->addSql('ALTER TABLE tipos_chaves_pix ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_contas_bancarias_id_seq');
        $this->addSql('SELECT setval(\'tipos_contas_bancarias_id_seq\', (SELECT MAX(id) FROM tipos_contas_bancarias))');
        $this->addSql('ALTER TABLE tipos_contas_bancarias ALTER id SET DEFAULT nextval(\'tipos_contas_bancarias_id_seq\')');
        $this->addSql('ALTER TABLE tipos_contas_bancarias ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_documentos_id_seq');
        $this->addSql('SELECT setval(\'tipos_documentos_id_seq\', (SELECT MAX(id) FROM tipos_documentos))');
        $this->addSql('ALTER TABLE tipos_documentos ALTER id SET DEFAULT nextval(\'tipos_documentos_id_seq\')');
        $this->addSql('ALTER TABLE tipos_documentos ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_emails_id_seq');
        $this->addSql('SELECT setval(\'tipos_emails_id_seq\', (SELECT MAX(id) FROM tipos_emails))');
        $this->addSql('ALTER TABLE tipos_emails ALTER id SET DEFAULT nextval(\'tipos_emails_id_seq\')');
        $this->addSql('ALTER TABLE tipos_emails ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_enderecos_id_seq');
        $this->addSql('SELECT setval(\'tipos_enderecos_id_seq\', (SELECT MAX(id) FROM tipos_enderecos))');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER id SET DEFAULT nextval(\'tipos_enderecos_id_seq\')');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tipos_enderecos ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_imoveis_id_seq');
        $this->addSql('SELECT setval(\'tipos_imoveis_id_seq\', (SELECT MAX(id) FROM tipos_imoveis))');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER id SET DEFAULT nextval(\'tipos_imoveis_id_seq\')');
        $this->addSql('ALTER TABLE tipos_imoveis ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_pessoas_id_seq');
        $this->addSql('SELECT setval(\'tipos_pessoas_id_seq\', (SELECT MAX(id) FROM tipos_pessoas))');
        $this->addSql('ALTER TABLE tipos_pessoas ALTER id SET DEFAULT nextval(\'tipos_pessoas_id_seq\')');
        $this->addSql('ALTER TABLE tipos_pessoas ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_remessa_id_seq');
        $this->addSql('SELECT setval(\'tipos_remessa_id_seq\', (SELECT MAX(id) FROM tipos_remessa))');
        $this->addSql('ALTER TABLE tipos_remessa ALTER id SET DEFAULT nextval(\'tipos_remessa_id_seq\')');
        $this->addSql('ALTER TABLE tipos_remessa ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE tipos_telefones_id_seq');
        $this->addSql('SELECT setval(\'tipos_telefones_id_seq\', (SELECT MAX(id) FROM tipos_telefones))');
        $this->addSql('ALTER TABLE tipos_telefones ALTER id SET DEFAULT nextval(\'tipos_telefones_id_seq\')');
        $this->addSql('ALTER TABLE tipos_telefones ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE users DROP created_at');
        $this->addSql('ALTER TABLE users DROP updated_at');
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('CREATE SEQUENCE users_id_seq');
        $this->addSql('SELECT setval(\'users_id_seq\', (SELECT MAX(id) FROM users))');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\')');
        $this->addSql('ALTER TABLE users ALTER remember_token TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER profile_photo_path TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ADD PRIMARY KEY (id)');
        $this->addSql('CREATE SEQUENCE messenger_messages_id_seq');
        $this->addSql('SELECT setval(\'messenger_messages_id_seq\', (SELECT MAX(id) FROM messenger_messages))');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\')');
        $this->addSql('ALTER TABLE messenger_messages ADD PRIMARY KEY (id)');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE fiadores_inquilinos DROP CONSTRAINT fiadores_inquilinos_pkey');
        $this->addSql('ALTER TABLE fiadores_inquilinos ADD data_inicio DATE NOT NULL');
        $this->addSql('ALTER TABLE fiadores_inquilinos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE failed_jobs DROP CONSTRAINT failed_jobs_pkey');
        $this->addSql('ALTER TABLE failed_jobs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE estados DROP CONSTRAINT estados_pkey');
        $this->addSql('ALTER TABLE estados ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE contas_vinculadas DROP CONSTRAINT contas_vinculadas_pkey');
        $this->addSql('ALTER TABLE contas_vinculadas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_imoveis DROP CONSTRAINT tipos_imoveis_pkey');
        $this->addSql('ALTER TABLE tipos_imoveis ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE estado_civil DROP CONSTRAINT estado_civil_pkey');
        $this->addSql('ALTER TABLE estado_civil ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE enderecos DROP CONSTRAINT FK_FC4E02DA3AE81E6F');
        $this->addSql('ALTER TABLE enderecos DROP CONSTRAINT FK_FC4E02DAF1B90DAB');
        $this->addSql('ALTER TABLE enderecos DROP CONSTRAINT FK_FC4E02DAFB0D0145');
        $this->addSql('DROP INDEX IDX_FC4E02DA3AE81E6F');
        $this->addSql('DROP INDEX IDX_FC4E02DAF1B90DAB');
        $this->addSql('DROP INDEX IDX_FC4E02DAFB0D0145');
        $this->addSql('ALTER TABLE enderecos DROP CONSTRAINT enderecos_pkey');
        $this->addSql('ALTER TABLE emails DROP CONSTRAINT FK_4C81E852FB0D0145');
        $this->addSql('DROP INDEX IDX_4C81E852FB0D0145');
        $this->addSql('ALTER TABLE emails DROP CONSTRAINT emails_pkey');
        $this->addSql('ALTER TABLE bancos DROP CONSTRAINT bancos_pkey');
        $this->addSql('ALTER TABLE bancos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_telefones DROP CONSTRAINT tipos_telefones_pkey');
        $this->addSql('ALTER TABLE tipos_telefones ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_enderecos DROP CONSTRAINT tipos_enderecos_pkey');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER created_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE tipos_enderecos ALTER updated_at TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE chaves_pix DROP CONSTRAINT chaves_pix_pkey');
        $this->addSql('ALTER TABLE tipos_remessa DROP CONSTRAINT tipos_remessa_pkey');
        $this->addSql('ALTER TABLE tipos_remessa ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_emails DROP CONSTRAINT tipos_emails_pkey');
        $this->addSql('ALTER TABLE tipos_emails ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_documentos DROP CONSTRAINT tipos_documentos_pkey');
        $this->addSql('ALTER TABLE tipos_documentos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_contas_bancarias DROP CONSTRAINT tipos_contas_bancarias_pkey');
        $this->addSql('ALTER TABLE tipos_contas_bancarias ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_chaves_pix DROP CONSTRAINT tipos_chaves_pix_pkey');
        $this->addSql('ALTER TABLE tipos_chaves_pix ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_carteiras DROP CONSTRAINT tipos_carteiras_pkey');
        $this->addSql('ALTER TABLE tipos_carteiras ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cidades DROP CONSTRAINT FK_79B94AE76A540E');
        $this->addSql('DROP INDEX IDX_79B94AE76A540E');
        $this->addSql('ALTER TABLE cidades DROP CONSTRAINT cidades_pkey');
        $this->addSql('ALTER TABLE cidades ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE bairros DROP CONSTRAINT FK_6BE5C8B64CAF86B1');
        $this->addSql('DROP INDEX IDX_6BE5C8B64CAF86B1');
        $this->addSql('ALTER TABLE bairros DROP CONSTRAINT bairros_pkey');
        $this->addSql('ALTER TABLE bairros ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_atendimento DROP CONSTRAINT tipos_atendimento_pkey');
        $this->addSql('ALTER TABLE tipos_atendimento ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE telefones DROP CONSTRAINT FK_219AAC26FB0D0145');
        $this->addSql('DROP INDEX IDX_219AAC26FB0D0145');
        $this->addSql('ALTER TABLE telefones DROP CONSTRAINT telefones_pkey');
        $this->addSql('ALTER TABLE configuracoes_cobranca DROP CONSTRAINT configuracoes_cobranca_pkey');
        $this->addSql('ALTER TABLE configuracoes_cobranca ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT users_pkey');
        $this->addSql('ALTER TABLE users ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE users ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE users ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER remember_token TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE users ALTER profile_photo_path TYPE VARCHAR(2048)');
        $this->addSql('ALTER TABLE sessions DROP CONSTRAINT sessions_pkey');
        $this->addSql('ALTER TABLE roles DROP CONSTRAINT roles_pkey');
        $this->addSql('ALTER TABLE roles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE role_has_permissions DROP CONSTRAINT role_has_permissions_pkey');
        $this->addSql('ALTER TABLE requisicoes_responsaveis DROP CONSTRAINT requisicoes_responsaveis_pkey');
        $this->addSql('ALTER TABLE requisicoes_responsaveis ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE relacionamentos_familiares DROP CONSTRAINT relacionamentos_familiares_pkey');
        $this->addSql('ALTER TABLE regimes_casamento DROP CONSTRAINT regimes_casamento_pkey');
        $this->addSql('ALTER TABLE regimes_casamento ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE razoes_conta DROP CONSTRAINT razoes_conta_pkey');
        $this->addSql('ALTER TABLE razoes_conta ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE agencias DROP CONSTRAINT FK_923688C0995BA0E1');
        $this->addSql('ALTER TABLE agencias DROP CONSTRAINT FK_923688C0A83B3A9B');
        $this->addSql('DROP INDEX IDX_923688C0995BA0E1');
        $this->addSql('DROP INDEX IDX_923688C0A83B3A9B');
        $this->addSql('ALTER TABLE agencias DROP CONSTRAINT agencias_pkey');
        $this->addSql('ALTER TABLE agencias ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE profissoes DROP CONSTRAINT profissoes_pkey');
        $this->addSql('ALTER TABLE pessoas_tipos DROP CONSTRAINT pessoas_tipos_pkey');
        $this->addSql('ALTER TABLE pessoas_tipos ALTER data_inicio SET DEFAULT CURRENT_DATE');
        $this->addSql('ALTER TABLE pessoas_telefones DROP CONSTRAINT pessoas_telefones_pkey');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT FK_E7120EDB3AE81E6F');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT FK_E7120EDB995BA0E1');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT FK_E7120EDB35F182E9');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT FK_E7120EDBEB6C0CDC');
        $this->addSql('DROP INDEX IDX_E7120EDB3AE81E6F');
        $this->addSql('DROP INDEX IDX_E7120EDB995BA0E1');
        $this->addSql('DROP INDEX IDX_E7120EDB35F182E9');
        $this->addSql('DROP INDEX IDX_E7120EDBEB6C0CDC');
        $this->addSql('ALTER TABLE contas_bancarias DROP CONSTRAINT contas_bancarias_pkey');
        $this->addSql('ALTER TABLE contas_bancarias ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE tipos_pessoas DROP CONSTRAINT tipos_pessoas_pkey');
        $this->addSql('ALTER TABLE tipos_pessoas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT FK_B57CEF673AE81E6F');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT FK_B57CEF671D873604');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT FK_B57CEF674D6C7D6D');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT FK_B57CEF67BAC6B6DF');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT FK_B57CEF67E90B7405');
        $this->addSql('DROP INDEX IDX_B57CEF673AE81E6F');
        $this->addSql('DROP INDEX IDX_B57CEF671D873604');
        $this->addSql('DROP INDEX IDX_B57CEF674D6C7D6D');
        $this->addSql('DROP INDEX IDX_B57CEF67BAC6B6DF');
        $this->addSql('DROP INDEX IDX_B57CEF67E90B7405');
        $this->addSql('ALTER TABLE pessoas_pretendentes DROP CONSTRAINT pessoas_pretendentes_pkey');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_pessoa TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_tipo_imovel TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_logradouro_desejado TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_atendente TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER id_tipo_atendimento TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_pretendentes ALTER aluguel_maximo TYPE NUMERIC(10, 0)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pessoas_pretendentes_id_pessoa ON pessoas_pretendentes (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_locadores DROP CONSTRAINT FK_99A9F08D3AE81E6F');
        $this->addSql('ALTER TABLE pessoas_locadores DROP CONSTRAINT FK_99A9F08DF1D3B3A1');
        $this->addSql('DROP INDEX IDX_99A9F08D3AE81E6F');
        $this->addSql('DROP INDEX IDX_99A9F08DF1D3B3A1');
        $this->addSql('ALTER TABLE pessoas_locadores DROP CONSTRAINT pessoas_locadores_pkey');
        $this->addSql('CREATE UNIQUE INDEX uniq_pessoas_locadores_id_pessoa ON pessoas_locadores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_fiadores DROP CONSTRAINT pessoas_fiadores_pkey');
        $this->addSql('CREATE UNIQUE INDEX uniq_pessoas_fiadores_id_pessoa ON pessoas_fiadores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_emails DROP CONSTRAINT pessoas_emails_pkey');
        $this->addSql('ALTER TABLE pessoas_documentos DROP CONSTRAINT FK_843B541B3AE81E6F');
        $this->addSql('ALTER TABLE pessoas_documentos DROP CONSTRAINT FK_843B541B69B92C8F');
        $this->addSql('DROP INDEX IDX_843B541B3AE81E6F');
        $this->addSql('DROP INDEX IDX_843B541B69B92C8F');
        $this->addSql('ALTER TABLE pessoas_documentos DROP CONSTRAINT pessoas_documentos_pkey');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_pessoa TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_pessoa SET NOT NULL');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_tipo_documento TYPE BIGINT');
        $this->addSql('ALTER TABLE pessoas_documentos ALTER id_tipo_documento SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_pessoas_documentos_pessoa_tipo_numero ON pessoas_documentos (id_pessoa, id_tipo_documento, numero_documento)');
        $this->addSql('ALTER TABLE pessoas_corretores DROP CONSTRAINT FK_E45C8F5B3AE81E6F');
        $this->addSql('DROP INDEX IDX_E45C8F5B3AE81E6F');
        $this->addSql('ALTER TABLE pessoas_corretores DROP CONSTRAINT pessoas_corretores_pkey');
        $this->addSql('CREATE UNIQUE INDEX uniq_pessoas_corretores_id_pessoa ON pessoas_corretores (id_pessoa)');
        $this->addSql('ALTER TABLE pessoas_corretoras DROP CONSTRAINT FK_80304A5F3AE81E6F');
        $this->addSql('DROP INDEX UNIQ_80304A5F3AE81E6F');
        $this->addSql('ALTER TABLE pessoas_corretoras DROP CONSTRAINT pessoas_corretoras_pkey');
        $this->addSql('ALTER TABLE pessoas_contratantes DROP CONSTRAINT FK_25184ED03AE81E6F');
        $this->addSql('ALTER TABLE pessoas_contratantes DROP CONSTRAINT pessoas_contratantes_pkey');
        $this->addSql('ALTER INDEX uniq_25184ed03ae81e6f RENAME TO uniq_pessoas_contratantes_id_pessoa');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT FK_18A4F2AC75376D93');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT FK_18A4F2AC21CE4288');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT FK_18A4F2AC76BE313');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT FK_18A4F2ACA76ED395');
        $this->addSql('DROP INDEX IDX_18A4F2AC75376D93');
        $this->addSql('DROP INDEX IDX_18A4F2AC21CE4288');
        $this->addSql('DROP INDEX IDX_18A4F2AC76BE313');
        $this->addSql('DROP INDEX UNIQ_18A4F2ACA76ED395');
        $this->addSql('ALTER TABLE pessoas DROP CONSTRAINT pessoas_pkey');
        $this->addSql('ALTER TABLE personal_access_tokens DROP CONSTRAINT personal_access_tokens_pkey');
        $this->addSql('ALTER TABLE personal_access_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE permissions DROP CONSTRAINT permissions_pkey');
        $this->addSql('ALTER TABLE permissions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE password_reset_tokens DROP CONSTRAINT password_reset_tokens_pkey');
        $this->addSql('ALTER TABLE naturalidades DROP CONSTRAINT naturalidades_pkey');
        $this->addSql('ALTER TABLE nacionalidades DROP CONSTRAINT nacionalidades_pkey');
        $this->addSql('ALTER TABLE model_has_roles DROP CONSTRAINT model_has_roles_pkey');
        $this->addSql('ALTER TABLE model_has_permissions DROP CONSTRAINT model_has_permissions_pkey');
        $this->addSql('ALTER TABLE messenger_messages DROP CONSTRAINT messenger_messages_pkey');
        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0');
        $this->addSql('DROP INDEX IDX_75EA56E0E3BD61CE');
        $this->addSql('DROP INDEX IDX_75EA56E016BA31DB');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE logradouros DROP CONSTRAINT FK_42E9C191A7C487E8');
        $this->addSql('DROP INDEX IDX_42E9C191A7C487E8');
        $this->addSql('ALTER TABLE logradouros DROP CONSTRAINT logradouros_pkey');
        $this->addSql('ALTER TABLE logradouros ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE layouts_remessa DROP CONSTRAINT layouts_remessa_pkey');
        $this->addSql('ALTER TABLE layouts_remessa ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE formas_retirada DROP CONSTRAINT formas_retirada_pkey');
        $this->addSql('ALTER TABLE formas_retirada ALTER id DROP DEFAULT');
    }
}
