<?php

namespace App\Tests\Entity;

use App\Entity\Cidades;
use App\Entity\Estados;
use PHPUnit\Framework\TestCase;

class CidadesTest extends TestCase
{
    public function testCreateCidade(): void
    {
        $cidade = new Cidades();
        $this->assertInstanceOf(Cidades::class, $cidade);
    }

    public function testCidadeGettersAndSetters(): void
    {
        $cidade = new Cidades();
        $mockEstado = $this->createMock(Estados::class);
        $nome = "São Paulo";
        $codigo = "3550308";

        $cidade->setEstado($mockEstado);
        $cidade->setNome($nome);
        $cidade->setCodigo($codigo);

        $this->assertSame($mockEstado, $cidade->getEstado());
        $this->assertEquals($nome, $cidade->getNome());
        $this->assertEquals($codigo, $cidade->getCodigo());
    }

    public function testCidadeId(): void
    {
        $cidade = new Cidades();
        
        // Test that ID starts as null (will be generated by DB)
        $this->assertNull($cidade->getId());
    }

    public function testCidadeCodigoNullable(): void
    {
        $cidade = new Cidades();
        
        // Test that codigo can be null
        $this->assertNull($cidade->getCodigo());
        
        // Test setting codigo to null
        $cidade->setCodigo(null);
        $this->assertNull($cidade->getCodigo());
    }

    public function testCidadeMethodsExist(): void
    {
        $cidade = new Cidades();

        // Test that all required methods exist
        $this->assertTrue(method_exists($cidade, 'getId'));
        $this->assertTrue(method_exists($cidade, 'getEstado'));
        $this->assertTrue(method_exists($cidade, 'setEstado'));
        $this->assertTrue(method_exists($cidade, 'getNome'));
        $this->assertTrue(method_exists($cidade, 'setNome'));
        $this->assertTrue(method_exists($cidade, 'getCodigo'));
        $this->assertTrue(method_exists($cidade, 'setCodigo'));
    }

    public function testCidadeWithDifferentEstados(): void
    {
        $cidade = new Cidades();

        // Test with different estado instances
        $mockEstados = [
            $this->createMock(Estados::class),
            $this->createMock(Estados::class),
            $this->createMock(Estados::class),
            $this->createMock(Estados::class),
            $this->createMock(Estados::class),
        ];

        foreach ($mockEstados as $mockEstado) {
            $cidade->setEstado($mockEstado);
            $this->assertSame($mockEstado, $cidade->getEstado());
        }
    }

    public function testCidadeNomeVariations(): void
    {
        $cidade = new Cidades();
        
        // Test with different city name formats
        $nomes = [
            "São Paulo",
            "Rio de Janeiro", 
            "Belo Horizonte",
            "Porto Alegre",
            "Curitiba"
        ];
        
        foreach ($nomes as $nome) {
            $cidade->setNome($nome);
            $this->assertEquals($nome, $cidade->getNome());
        }
    }

    public function testCidadeCodigoFormats(): void
    {
        $cidade = new Cidades();
        
        // Test with different IBGE code formats
        $codigos = [
            "3550308", // São Paulo
            "3304557", // Rio de Janeiro
            "3106200", // Belo Horizonte
            "4314902", // Porto Alegre
            "4106902"  // Curitiba
        ];
        
        foreach ($codigos as $codigo) {
            $cidade->setCodigo($codigo);
            $this->assertEquals($codigo, $cidade->getCodigo());
        }
    }
}
