<?php

namespace App\Tests\Entity;

use App\Entity\Enderecos;
use PHPUnit\Framework\TestCase;

class EnderecosTest extends TestCase
{
    public function testCreateEndereco(): void
    {
        $endereco = new Enderecos();
        $this->assertInstanceOf(Enderecos::class, $endereco);
    }

    public function testEnderecoGettersAndSetters(): void
    {
        $endereco = new Enderecos();
        $mockPessoa = $this->createMock(\App\Entity\Pessoas::class);
        $mockLogradouro = $this->createMock(\App\Entity\Logradouros::class);
        $mockTipo = $this->createMock(\App\Entity\TiposEnderecos::class);
        $endNumero = 456;
        $complemento = "Apto 101";

        $endereco->setPessoa($mockPessoa);
        $endereco->setLogradouro($mockLogradouro);
        $endereco->setTipo($mockTipo);
        $endereco->setEndNumero($endNumero);
        $endereco->setComplemento($complemento);

        $this->assertSame($mockPessoa, $endereco->getPessoa());
        $this->assertSame($mockLogradouro, $endereco->getLogradouro());
        $this->assertSame($mockTipo, $endereco->getTipo());
        $this->assertEquals($endNumero, $endereco->getEndNumero());
        $this->assertEquals($complemento, $endereco->getComplemento());
    }

    public function testEnderecoId(): void
    {
        $endereco = new Enderecos();
        
        // Test that ID starts as null (will be generated by DB)
        $this->assertNull($endereco->getId());
    }

    public function testEnderecoComplementoNullable(): void
    {
        $endereco = new Enderecos();
        
        // Test that complemento can be null
        $this->assertNull($endereco->getComplemento());
        
        // Test setting complemento to null
        $endereco->setComplemento(null);
        $this->assertNull($endereco->getComplemento());
    }

    public function testEnderecoMethodsExist(): void
    {
        $endereco = new Enderecos();

        // Test that all required methods exist
        $this->assertTrue(method_exists($endereco, 'getId'));
        $this->assertTrue(method_exists($endereco, 'getPessoa'));
        $this->assertTrue(method_exists($endereco, 'setPessoa'));
        $this->assertTrue(method_exists($endereco, 'getLogradouro'));
        $this->assertTrue(method_exists($endereco, 'setLogradouro'));
        $this->assertTrue(method_exists($endereco, 'getTipo'));
        $this->assertTrue(method_exists($endereco, 'setTipo'));
        $this->assertTrue(method_exists($endereco, 'getEndNumero'));
        $this->assertTrue(method_exists($endereco, 'setEndNumero'));
        $this->assertTrue(method_exists($endereco, 'getComplemento'));
        $this->assertTrue(method_exists($endereco, 'setComplemento'));
    }

    public function testEnderecoNumeroValues(): void
    {
        $endereco = new Enderecos();
        
        // Test with different number values
        $numeros = [1, 100, 999, 1234, 9999];
        
        foreach ($numeros as $numero) {
            $endereco->setEndNumero($numero);
            $this->assertEquals($numero, $endereco->getEndNumero());
        }
    }

    public function testEnderecoComplementoVariations(): void
    {
        $endereco = new Enderecos();
        
        // Test with different complement formats
        $complementos = [
            "Apto 101",
            "Casa A",
            "Bloco 2",
            "Sala 503",
            "Fundos",
            "Térreo",
            "2º Andar"
        ];
        
        foreach ($complementos as $complemento) {
            $endereco->setComplemento($complemento);
            $this->assertEquals($complemento, $endereco->getComplemento());
        }
    }

    public function testEnderecoIdRelationships(): void
    {
        $endereco = new Enderecos();

        // Test with different entity relationships
        $mockPessoa = $this->createMock(\App\Entity\Pessoas::class);
        $mockLogradouro = $this->createMock(\App\Entity\Logradouros::class);
        $mockTipo = $this->createMock(\App\Entity\TiposEnderecos::class);

        $endereco->setPessoa($mockPessoa);
        $endereco->setLogradouro($mockLogradouro);
        $endereco->setTipo($mockTipo);

        $this->assertSame($mockPessoa, $endereco->getPessoa());
        $this->assertSame($mockLogradouro, $endereco->getLogradouro());
        $this->assertSame($mockTipo, $endereco->getTipo());
    }

    public function testEnderecoFluentInterface(): void
    {
        $endereco = new Enderecos();

        // Test that setters return self for fluent interface
        $mockPessoa = $this->createMock(\App\Entity\Pessoas::class);
        $mockLogradouro = $this->createMock(\App\Entity\Logradouros::class);
        $mockTipo = $this->createMock(\App\Entity\TiposEnderecos::class);

        $result = $endereco->setPessoa($mockPessoa)
                          ->setLogradouro($mockLogradouro)
                          ->setTipo($mockTipo)
                          ->setEndNumero(123)
                          ->setComplemento("Apto 101");

        $this->assertSame($endereco, $result);
        $this->assertSame($mockPessoa, $endereco->getPessoa());
        $this->assertSame($mockLogradouro, $endereco->getLogradouro());
        $this->assertSame($mockTipo, $endereco->getTipo());
        $this->assertEquals(123, $endereco->getEndNumero());
        $this->assertEquals("Apto 101", $endereco->getComplemento());
    }
}
