<?php

namespace App\Tests\Entity;

use App\Entity\Logradouros;
use PHPUnit\Framework\TestCase;

class LogradourosTest extends TestCase
{
    public function testCreateLogradouro(): void
    {
        $logradouro = new Logradouros();
        $this->assertInstanceOf(Logradouros::class, $logradouro);
    }

    public function testLogradouroGettersAndSetters(): void
    {
        $logradouro = new Logradouros();
        $mockBairro = $this->createMock(\App\Entity\Bairros::class);
        $logradouroNome = "Rua das Flores";
        $cep = "01234-567";

        $logradouro->setBairro($mockBairro);
        $logradouro->setLogradouro($logradouroNome);
        $logradouro->setCep($cep);

        $this->assertSame($mockBairro, $logradouro->getBairro());
        $this->assertEquals($logradouroNome, $logradouro->getLogradouro());
        $this->assertEquals('01234567', $logradouro->getCep()); // setCep strips non-digits
    }

    public function testLogradouroId(): void
    {
        $logradouro = new Logradouros();
        
        // Test that ID starts as null (will be generated by DB)
        $this->assertNull($logradouro->getId());
    }

    public function testLogradouroMethodsExist(): void
    {
        $logradouro = new Logradouros();

        // Test that all required methods exist
        $this->assertTrue(method_exists($logradouro, 'getId'));
        $this->assertTrue(method_exists($logradouro, 'getBairro'));
        $this->assertTrue(method_exists($logradouro, 'setBairro'));
        $this->assertTrue(method_exists($logradouro, 'getLogradouro'));
        $this->assertTrue(method_exists($logradouro, 'setLogradouro'));
        $this->assertTrue(method_exists($logradouro, 'getCep'));
        $this->assertTrue(method_exists($logradouro, 'setCep'));
    }

    public function testLogradouroNomeVariations(): void
    {
        $logradouro = new Logradouros();
        
        // Test with different street types
        $logradouros = [
            "Rua das Flores",
            "Avenida Paulista",
            "Travessa do Comércio",
            "Alameda Santos",
            "Praça da Sé",
            "Largo do Arouche",
            "Via Expressa",
            "Estrada de Santos"
        ];
        
        foreach ($logradouros as $nome) {
            $logradouro->setLogradouro($nome);
            $this->assertEquals($nome, $logradouro->getLogradouro());
        }
    }

    public function testLogradouroCepFormats(): void
    {
        $logradouro = new Logradouros();
        
        // Test with different CEP formats
        // setCep strips non-digit characters
        $cepTests = [
            ["01234-567", "01234567"],
            ["04567-890", "04567890"],
            ["12345678", "12345678"],
            ["00000-000", "00000000"],
            ["99999-999", "99999999"],
        ];

        foreach ($cepTests as [$input, $expected]) {
            $logradouro->setCep($input);
            $this->assertEquals($expected, $logradouro->getCep());
        }
    }

    public function testLogradouroBairroRelationship(): void
    {
        $logradouro = new Logradouros();

        // Test with different bairro entities
        $mockBairro = $this->createMock(\App\Entity\Bairros::class);
        $logradouro->setBairro($mockBairro);
        $this->assertSame($mockBairro, $logradouro->getBairro());
    }

    public function testLogradouroFluentInterface(): void
    {
        $logradouro = new Logradouros();

        // Test that setters return self for fluent interface
        $mockBairro = $this->createMock(\App\Entity\Bairros::class);

        $result = $logradouro->setBairro($mockBairro)
                            ->setLogradouro("Rua das Flores")
                            ->setCep("01234-567");

        $this->assertSame($logradouro, $result);
        $this->assertSame($mockBairro, $logradouro->getBairro());
        $this->assertEquals("Rua das Flores", $logradouro->getLogradouro());
        $this->assertEquals("01234567", $logradouro->getCep()); // setCep strips non-digits
    }

    public function testLogradouroSpecialCharacters(): void
    {
        $logradouro = new Logradouros();
        
        // Test with special characters in street names
        $nomesEspeciais = [
            "Rua São João",
            "Avenida dos Três Poderes",
            "Travessa João & Maria",
            "Alameda São José dos Campos",
            "Praça D. Pedro II"
        ];
        
        foreach ($nomesEspeciais as $nome) {
            $logradouro->setLogradouro($nome);
            $this->assertEquals($nome, $logradouro->getLogradouro());
        }
    }
}
